version: "3"
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=jefao123
      - MYSQL_DATABASE=vip-conference
      - MYSQL_USER=jefao
      - MYSQL_PASSWORD=jefao
    networks: 
      - conference
    volumes:
    - ./dbdata:/var/lib/mysql
  
  nodeapp:
    build: ../
    environment:
      - NODE_ENV=production
    networks: 
      - conference
    volumes: 
      - /root/.jitsi-meet-cfg/jibri/recordings:/records
  
  proxy:
        image: nginx
        volumes:
            - ./conf:/etc/nginx/conf.d/
            - /root/.jitsi-meet-cfg/web/acme-certs/meet.vipsolutions.com.br:/etc/nginx/certs/
        networks:
            - conference
        ports:
            - 8000:443

networks: 
 conference: